version: '3.4'

services:
  goblocal-geoserver:
    image: oscarfonts/geoserver:2.15.0
    ports:
     - '8080:8080'    


  goblocal-inicio:
    image: diegodob/goblocal-inicio:0.2
    depends_on:
      - goblocal-geoserver
    env_file:
      - goblocal-inicio.env
    command: >
      bash -c "git clone https://github.com/diegodob/goblocal-datos-ejemplo /opt/goblocal-inicio/datos &&
               /opt/goblocal-inicio/wait-goblocal-geoserver.sh $$GEOSERVER_URL &&
               python /opt/goblocal-inicio/goblocal-inicio.py $$GEOSERVER_URL $$GEOSERVER_USER $$GEOSERVER_PASSWORD"
  goblocal-visualizador:
    image: httpd:2.4
    ports:
     - '8888:80'    
    command: >
      bash -c "echo ""El visualizador será descargado del siguiente repositorio GIT: $$GIT_REPO_URL"" && apt-get update &&
      apt-get install git -y && 
      rm -r /usr/local/apache2/htdocs/ && 
      git clone https://github.com/diegodob/goblocal-visualizador /usr/local/apache2/htdocs/ &&
      httpd-foreground"
