version: '3.4'

services:
  goblocal-geoserver:
    image: oscarfonts/geoserver:2.15.0
    ports:
     - '8080:8080'    


  goblocal-inicio:
    image: diegodob/goblocal-inicio:0.3
    depends_on:
      - goblocal-geoserver
    env_file:
      - goblocal-inicio.env
    command: >
      bash -c "echo \"Los datos serán descargados del siguiente repositorio GIT: $$GIT_REPOSITORIO_DATOS_URL\"
               git clone $$GIT_REPOSITORIO_DATOS_URL /opt/goblocal-inicio/datos &&
               /opt/goblocal-inicio/wait-goblocal-geoserver.sh $$GEOSERVER_URL &&
               python /opt/goblocal-inicio/goblocal-inicio.py $$GEOSERVER_URL $$GEOSERVER_USER $$GEOSERVER_PASSWORD"
  goblocal-visualizador:
    image: httpd:2.4
    ports:
     - '8888:80'    
    env_file:
      - goblocal-visualizador.env
    command: >
      bash -c "echo ""El visualizador será descargado del siguiente repositorio GIT: $$GIT_REPOSITORIO_URL"" && apt-get update &&
      apt-get install git -y && 
      rm -r /usr/local/apache2/htdocs/ && 
      git clone $$GIT_REPOSITORIO_VISUALIZADOR_URL /usr/local/apache2/htdocs/ &&
      sed -i "s,http://localhost:8080/,$$GOBLOCAL_GEOSERVER_URL_EXTERNA,g" /usr/local/apache2/htdocs/js/menu.json &&
      httpd-foreground"
