version: '3.4'

services:
  goblocal-geoserver:
    image: oscarfonts/geoserver:2.15.1
    ports:
     - '8080:8080'    
    command: >
      bash -c "cd /usr/local/geoserver/WEB-INF/lib &&
              wget https://razaoinfo.dl.sourceforge.net/project/geoserver/GeoServer/2.15.1/extensions/geoserver-2.15.1-vectortiles-plugin.zip &&
              unzip -o geoserver-2.15.1-vectortiles-plugin.zip &&
              rm geoserver-2.15.1-vectortiles-plugin.zip &&
              start.sh"


  goblocal-inicio:
    image: diegodob/goblocal-inicio:0.4
    depends_on:
      - goblocal-geoserver
    env_file:
      - goblocal-inicio.env
    command: >
      bash -c "echo \"Los datos serán descargados del siguiente repositorio GIT: $$GIT_REPOSITORIO_DATOS_URL\"
               git clone $$GIT_REPOSITORIO_DATOS_URL /opt/goblocal-inicio/datos &&
               /opt/goblocal-inicio/wait-goblocal-geoserver.sh $$GEOSERVER_URL &&
               python /opt/goblocal-inicio/goblocal-inicio.py $$GEOSERVER_URL $$GEOSERVER_USER $$GEOSERVER_PASSWORD"
  goblocal-visualizador:
    image: php:7.3-apache-stretch
    ports:
     - '8888:80'    
    env_file:
      - goblocal-visualizador.env
    command: >
      bash -c "echo ""El visualizador será descargado del siguiente repositorio GIT: $$GIT_REPOSITORIO_URL"" && apt-get update &&
      apt-get install git -y && 
      git clone $$GIT_REPOSITORIO_VISUALIZADOR_URL /var/www/html &&
      sed -i "s,http://localhost:8080/,$$GOBLOCAL_GEOSERVER_URL_EXTERNA,g" /var/www/html/js/menu.json &&
      apache2-foreground"
