version: '3.4'

services:
  geoserver:
    image: oscarfonts/geoserver:2.15.0
    ports:
     - '8000:8080'    


  geoserver_prepare:
    image: diegodob/prepare_geoserver:0.1
    depends_on:
      - geoserver
    env_file:
      - prepare_geoserver.env
    command: >
      bash -c "/opt/prepare_geoserver/wait_geoserver.sh $$GEOSERVER_URL &&
      python /opt/prepare_geoserver/prepare_geoserver.py $$GEOSERVER_URL $$GEOSERVER_USER $$GEOSERVER_PASSWORD"
