version: '3.4'

services:
  geoserver:
    image: oscarfonts/geoserver:2.15.0
    ports:
     - '8000:80'    
    healthcheck:
      test: ["CMD-SHELL", "curl -f 'http://localhost:8080/geoserver/ows?service=wms&version=1.3.0&request=GetCapabilities' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  geoserver_prepare:
    image: diegodob/geoserver_prepare:lastest
    depends_on:
      - geoserver

    links:
      - geoserver
